export const FETCH_SHIFTS_REQUEST = "FETCH_SHIFTS_REQUEST";
export const FETCH_SHIFTS_SUCCESS = "FETCH_SHIFTS_SUCCESS";
export const FETCH_SHIFTS_FAILURE = "FETCH_SHIFTS_FAILURE";
export const POST_SHIFT_REQUEST = "POST_SHIFT_REQUEST";
export const POST_SHIFT_SUCCESS = "POST_SHIFT_SUCCESS";
export const POST_SHIFT_FAILURE = "POST_SHIFT_FAILURE";
